name: cryptolake
version: "1.0.0"
config-version: 2

profile: cryptolake

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cryptolake:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: gold

on-run-start:
  - "CREATE NAMESPACE IF NOT EXISTS cryptolake.staging"
  - "CREATE NAMESPACE IF NOT EXISTS cryptolake.gold"
